definitions:
  contracts.ErrorResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      transactionId:
        type: string
    type: object
  contracts.HealthResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Api will return 200 if the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contracts.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/contracts.ErrorResponse'
      summary: Api to check the health of the service
      tags:
      - Health
swagger: "2.0"
